name: Tests
# only one can run at a time
concurrency:
  # If PR, cancel prev commits. head_ref = source branch name on pull_request, null if push
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [22.4]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          check-latest: true
          cache: npm
      - name: Initialize git submodules
        shell: bash
        run: git submodule init && git submodule update
      - name: Install & build
        shell: bash
        run: npm install && npm run build
      - name: Check Build
        shell: bash
        run: npm run check:build

  unit-tests:
    name: Unit Tests
    needs: ["build"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node: [22.4]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
          check-latest: true
          cache: npm
      - name: Initialize git submodules
        shell: bash
        run: git submodule init && git submodule update
      - name: Install & build
        shell: bash
        run: npm install && npm run build
      - name: Unit tests
        run: npm run test:unit
